[build]
  command = "npm run build:netlify"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_APP_URL,NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY,LIVEKIT_URL,LIVEKIT_API_KEY,LIVEKIT_API_SECRET"

[[plugins]]
  package = "@netlify/plugin-nextjs"

